
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  chaskiq:
    image: chaskiq/chaskiq:latest
    container_name: chaskiq
    restart: unless-stopped
    ports:
      - "3000:3000"

