
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - bw-data:/data

volumes:
  bw-data:
