
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  gimp:
    image: linuxserver/gimp:latest
    container_name: gimp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000

