
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  krita:
    image: linuxserver/krita:latest
    container_name: krita
    restart: unless-stopped
    ports:
      - "3000:3000"

