
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  librecad:
    image: lscr.io/linuxserver/librecad:latest
    container_name: librecad
    restart: unless-stopped
    ports:
      - "3000:3000"

