
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  jitsu:
    image: jitsu/jitsu:latest
    container_name: jitsu
    restart: unless-stopped
    ports:
      - "8000:8000"

