
# -------------------------------------------------------------------------
# ğŸš€ Created and distributed by The AltStack
# ğŸŒ https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  signoz-frontend:
    image: signoz/frontend:latest
    container_name: signoz-frontend
    restart: unless-stopped
    ports:
      - "3301:3301"

